name: Quick Tests

on:
  pull_request:
    paths-ignore:
    - 'doc/**'
  push:
    branches:
    - master
    - 'release-*'

jobs:
  ios:
    name: ${{ matrix.name }}
    runs-on: macos-latest
    strategy:
      matrix:
        include:
          - name: ios
            sdk: iphoneos
          - name: ios_simulator
            sdk: iphonesimulator
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: |
            brew install autoconf automake libtool pkg-config
      - name: set SDK-related env variables
        run: |
            echo "SDKROOT=$(xcrun --sdk ${{ matrix.sdk }} --show-sdk-path)" >> $GITHUB_ENV
      - name: super-test
        run: ./super-test.sh quick
